### ISSUE TITLE
Wearedata

### ISSUE THREAD

**Issue by AddBrickDevs** [tetreum/wearedata#2]
When does the Project Finished?

**Comment by tetreum** [comment]
Maybe when someone helps coding instead of waiting to have the project finished :o

**Comment by AddBrickDevs** [comment]
I can help you :)

**Comment by tetreum** [comment]
1. Go to assets/xml/config.xml and edit this line to point to a local server:
<path url="http://wearedata.watchdogs.com/amfserver.php"/>

2. Services/WatchDog.php is the class what will be called on eah swf petition (by https://github.com/tetreum/wearedata/blob/master/amfserver.php#L17). This file contains an output example of each query, so you just need to replicate that output on each call.
(Some data at https://github.com/tetreum/wearedata/blob/master/Services/WatchDog.php is hardcoded because was used for testing)

**Comment by RawliBeast** [comment]
Whenever I open it, it's just a black screen.
